version: '3'

services:
  inference_test:
    image: c4tiiv0/mlops-puj
    container_name: inference_test
    deploy: 
      mode: replicated
      replicas: 1

      resources: 
        limits: 
          cpus: '2'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    ports:
      - '8085:8085'
    restart: always
