version: '3.8'

services:
  inference_test:
    image: dcrovo/mlops_taller4:inference
    container_name: inference_test
    deploy: 
      mode: replicated
      replicas: 1

      resources: 
        limits: 
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - '8084:80'
    restart: always
    networks:
      - network1

networks:
  network1:
    name: testing_default
    driver: bridge
    external: true
